---
$all:
  Bus:
    Commands: amqp://guest:guest@localhost
    Queries:  amqp://guest:guest@localhost
    Events:   tcp://admin:changeit@localhost:1113
    States:   tcp://admin:changeit@localhost:1113

Example:
  data: Hello